### ISSUE TITLE
Failed to load the ide-laravel package

### ISSUE THREAD

**Issue by TurkMvc** [GeneaLabs/ide-laravel#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.1 ia32
**Electron**: 1.6.16
**OS**: Unknown Windows version
**Thrown From**: [ide-laravel](https://github.com/GeneaLabs/ide-laravel) package 0.0.0-prerelease

### Stack Trace

Failed to load the ide-laravel package

```
At Unexpected identifier

SyntaxError: Unexpected identifier
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.24.1/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.24.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.24.1/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.24.1/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.24.1/resources/app/src/package-manager.js:689:23)
    at ~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.24.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.24.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.24.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:44.6.0 core:confirm (input.hidden-input)
     -1:36.7.0 core:select-all (input.hidden-input)
     -1:35.4.0 core:backspace (input.hidden-input)
  2x -1:28.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
artisan 0.3.2 
ide-laravel 0.0.0-prerelease 
laravel-docs 1.0.3 
```

**Comment by Finnesko7** [comment]
Failed to load the ide-laravel package

**Comment by emayljames** [comment]
Exact same problem as OP. Package doesn't work.

**Comment by alextesi** [comment]
Exact same problem as OP. Package doesn't work.

**Comment by mikebronner** [comment]
Package is currently not functional, unfortunately. Waiting on a dependency: https://github.com/bmewburn/intelephense-server/issues/1

**Comment by AinCoder** [comment]
It's same here. :'(
